### PR TITLE
Don't appIcon.destroy() in click event

### LINKED ISSUE #220: Crash upon removing Tray icon twice
* OS X 10.10.5, node v6.2.1

Steps to reproduce:
1) Click "Put your app in the tray"
2) Click "Tray" to expand
3) Click "View Demo"
4) Click the tray icon in the menubar
5) Click "Remove" in the expanded tray icon
6) Click "View Demo" (if no crash, repeat starting at step 3)

I tried adding `if (appIcon)` in all locations appIcon was accessed in main-process/native-ui/tray/tray.js and also tried setting `appIcon = null` after any appIcon.destroy(), but both still produce crashes.

### PR DESCRIPTION
**Pull request by jlord**
Don't call `appIcon.destroy()` in the click event, because it causes a crash in OS X 10.10.x. Instead, use `ipc` and the `remove-tray` channel. 

Closes #220

### CODE REVIEW

**Comment by zeke** [comment]
Yeah this is kind of a bummer. You might be able to make the code a little more terse though:

```js
setImmediate(appIcon.destroy)
```

File: main-process/native-ui/tray/tray.js [hunk 1]
```diff
@@ -15,17 +15,25 @@ ipc.on('put-in-tray', function (event) {
     label: 'Remove',
     click: function () {
       event.sender.send('tray-removed')
-      appIcon.destroy()
```
Comment (kevinsawicki) [inline main-process/native-ui/tray/tray.js]: I think the crash only happens when called in a click handler right?

So perhaps calling `ipc.send('remove-tray')` after this line would make it so we don't even need to destroy it from this click handler https://github.com/electron/electron-api-demos/blob/8d71761cb0eae35034c8649dd5f24595bbee870b/renderer-process/native-ui/tray/tray.js#L21

Comment (jlord) [inline main-process/native-ui/tray/tray.js]: Ah, good call. I've updated it 👍
