### PR TITLE
check Heroku login status before release

### LINKED ISSUE #267: Release process hangs on Heroku deployment step
Output is stuck at this:

```
Zipping Electron API Demos.app to electron-api-demos-mac.zip
Zipping ElectronAPIDemos-win32-ia32 to electron-api-demos-windows.zip
Zipping Electron API Demos-linux-x64 to electron-api-demos-linux.zip
Creating new draft release
Uploading electron-api-demos-mac.zip as release asset
Uploading electron-api-demos-windows.zip as release asset
Uploading electron-api-demos-linux.zip as release asset
Uploading RELEASES as release asset
Uploading ElectronAPIDemosSetup.exe as release asset
Uploading ElectronAPIDemos-1.2.0-full.nupkg as release asset
Publishing release
Deploying to heroku
```

When I try to access the app's config in another tab:

```
❯ heroku config -a github-electron-api-demos
 ▸    Invalid credentials provided.
Enter your Heroku credentials.
Email: 
```

So I think the process is just hanging on this stdin thing.

@kevinsawicki any thoughts on how to make this fail when not logged in (or even better, ask for creds on the fly)? Maybe a `heroku whoami` check before?

### PR DESCRIPTION
**Pull request by zeke**
Fixes #267 

This runs `heroku whoami` before building the release and fails with a helpful message if the user is not logged in (or is logged in with a non-github.com email address.)

@kevinsawicki @Haacked

### CODE REVIEW

File: script/release.js [hunk 1]
```diff
@@ -28,6 +30,26 @@ function checkToken () {
...
 }
 
+function checkHerokuLoginStatus () {
+  return new Promise((resolve, reject) => {
+    console.log('Checking Heroku login status')
+
+    childProcess.exec('heroku whoami', (error, stdout, stderr) => {
+      if (error || !stdout.match('github.com')) {
+        reject(dedent`
+          You are not logged in to GitHub's Heroku Enterprise account
```
Comment (kevinsawicki) [inline script/release.js]: Is this app on Heroku Enterprise? I thought it wasn't.
